### ISSUE TITLE
Ошибки в модуле

### ISSUE THREAD

**Issue by lavkalavkalavka** [yoomoney/cms-opencart15#43]
1. После установки модуля в логе постоянное сообщение: PHP Warning:  strtolower() expects parameter 1 to be string, array given in /vqmod/vqcache/vq2-admin_view_template_sale_order_list.tpl on line 27
Строка 27 это: <a href="<?php echo $sort_order; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_order_id; ?></a>

2. Заголовок страницы "Заказы" в админке (/admin/index.php?route=sale/order) изменился на "ЮMoney"

**Comment by ostulov** [comment]
Добрый день!

Напишите, пожалуйста, что у Вас в 27 строке? В предыдущем сообщении код не прикрепился.

**Comment by lavkalavkalavka** [comment]
`<a href="<?php echo $sort_order; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_order_id; ?></a>`

**Comment by ostulov** [comment]
Благодарю за информацию, подготовим исправление!

**Comment by ostulov** [comment]
Исправление сделано в версии v2.0.8

**Comment by lavkalavkalavka** [comment]
Спасибо, работает ок!
